### PR TITLE
Updated jsdom to v11.11.0

### PR DESCRIPTION
**Pull request by DinkDonk**

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @DinkDonk! Thanks for working on this.

I must admit it's been a while since I looked at this codebase, since I'm no longer involved in the project it was developed for.

I remember us trying to update `jsdom` here before and finding that there had been some significant API changes that would require this library to be refactored before the upgrade could complete. However, that was a couple years ago now and so I don't remember all the details; perhaps that no longer applies.

Were you able to verify that this worked correctly in a real application with this new version of jsdom? I see that there are some Travis-CI failures, but I expect that's just because we're running the tests in some old versions of Node and some of the dependencies are presumably using newer JS features by now.

**Comment by DinkDonk** [comment]
I couldn't see any faults in practical use.
I made the upgrade to see if there was some performance benefits to be had – I didn't see much of that either :blush:

**Comment by apparentlymart** [comment]
Hi @DinkDonk! Thanks for following up.

In master I've updated the `.travis.yml` to test in the currently-active Node releases 6, 8, and 10, removing 4 and 5 which are now obsolete. If you wouldn't mind rebasing this to latest master and pushing again we should hopefully see the Travis checks be green in all three versions, in which case we can just add a suitable engine version constraint to `package.json` and this'll be good to go.

Thanks again for working on this!

**Comment by DinkDonk** [comment]
Good to go!

Thanks for sharing the code in the first place!
It's only right that I should help out in any small way I can 😃

**Comment by apparentlymart** [comment]
Thanks!

I'm not in the right environment to be able to release a new version to npm right now unfortunately, but hopefully you can install from git in the mean time. :confounded:

**Pull request merged**
