### PR TITLE
Fix runFile with updated jsdom

### PR DESCRIPTION
**Pull request by rjmackay**
- runFile was breaking because window.run didn't exist
- Added tests for runFile
- Cherry-picked a commit from @rit to fix the issue

### CODE REVIEW

**Comment by thrashr888** [comment]
I was hacking on this a bit myself.

This is great but the tests don't pass. It's just a jshint error so it should be easy to fix.

`lib/main.js: line 28, col 26, Missing space after 'function'.`

**Comment by rjmackay** [comment]
Fixed - however I've now noticed `example/helloworld.js` is still failing
```
$ node examples/helloworld.js 
/Users/robbie/devel/node-angularcontext/lib/main.js:180
            var $injector = rawContext.angular.injector(modules);
                                              ^

TypeError: Cannot read property 'injector' of undefined
    at Object.injector (/Users/robbie/devel/node-angularcontext/lib/main.js:180:47)
    at /Users/robbie/devel/node-angularcontext/examples/helloworld.js:12:32
    at runSources (/Users/robbie/devel/node-angularcontext/lib/main.js:48:17)
    at ReadFileContext.callback (/Users/robbie/devel/node-angularcontext/lib/main.js:80:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
```

**Comment by rjmackay** [comment]
Looking at how this is done in jsdom itself: it seems they now append a `<script>` tag and then remove it.. I suspect we might have to do the same.
This would all be much easier if we could use the `jsdom.env` api but I'm not clear if that would cover the full usecase for `angularcontext`

**Comment by rjmackay** [comment]
.. actually ignore me. The example works but it was just loading angular from the wrong place. Minor issue only

**Comment by thrashr888** [comment]
Tested locally. Looks good. Thanks for the upgrade. :)

**Pull request merged**
